apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: audiobookshelf-audiobooks
  name: audiobookshelf-audiobooks
  namespace: default
spec:
  storageClassName: nfs-audiobookshelf
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
