apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: audiobookshelf-config
  name: audiobookshelf-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: "longhorn"
