apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: audiobookshelf-metadata
  name: audiobookshelf-metadata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: "longhorn"