apiVersion: v1
kind: Secret
metadata:
    name: test-secret
    namespace: default
type: Opaque
stringData:
    test-secret: ENC[AES256_GCM,data:CLsSAuIvyZXDDKsfEePPQ/QsIt+i/sukug==,iv:QQK4EpB0oq5Gj/ddbS2mtoYdP0KtzjlY7MvEFYzZTCA=,tag:mK1uT7e08Tv5fdxdbsTExQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f38l3w2h64surqtq8qtcqqg9lfs7qqmtw8g9xp22fwl4esgcyvzsv4yjsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdmUwYUNTeE1rTzRyUjRR
            Z0YrcUQ3S1kydGlvbjRiR1MvcC9LOXRPRVZ3Clc4Qy84K25MaWlUMGs5aC9jOEsw
            R09KSVg3TnJnSGpIdVJSMGR0OVYzTDgKLS0tIDBvRTNZT3BHWmp5ZkV1UGU0VGZl
            ZnRHdFlrTzQzd0pGTEhVa2tNYVFEQkUKM6+CXOJl3fQVfN3QnZEKKy26cgKAwV6K
            71Jen/R1atomQE7i26IZxa0E/2Blb9gUwcFZxlwDduMck2CGqJcApA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-10T17:45:42Z"
    mac: ENC[AES256_GCM,data:K0EwYI/lze5rca43xtgHRqYpu2E1KJHTu3dzWlQCnVGG7UGcvgdSMNmNSlEQBJjnG6yGGiVPGqeO7nY/OqbdvrqyPh8EFj4u7unJ0VQkUba+m9OINGWCodKKy8MmMI4V1oeM6c4ouhfHPYV/sIwidgfiq3Ln4XREcId+jK40dKc=,iv:HsiKJvSv0dCfSPBRyDNdHnmNsYuX+GLCO/2Y8ZKjQW4=,tag:tY8BhNW+TAiPSO5PDb19eQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
