---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-unrelated-family-staging
  namespace: default
spec:
  secretTemplate:
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  secretName: local-unrelated-family-tls-staging
  commonName: "*.local.unrelated.family"
  dnsNames:
    - "local.unrelated.family"
    - "*.local.unrelated.family"