---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ade1987@pm.me
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: ade1987@pm.me
            apiTokenSecretRef:
              name: cf-token
              key: cloudflare-token
        selector:
          dnsZones:
            - "unrelated.family"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ade1987@pm.me
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: ade1987@pm.me
            apiTokenSecretRef:
              name: cf-token
              key: cloudflare-token
        selector:
          dnsZones:
            - "unrelated.family"