global:
    storageClass: ENC[AES256_GCM,data:vYJw5A+bN/A=,iv:gFmY4qg3vNoztEXCwQy5KXjhgLk8klQMBYf5wHxZV8Q=,tag:zJ3qcEhcky+huplNoHr4yg==,type:str]
pgpool:
    customUsers:
        usernames: ENC[AES256_GCM,data:p1cz7PmGkQCYEn8zTOM/UQ==,iv:BC5xXQXhFgclXaQB+pG3leBYdxtGiZPlSa/2Is/QzRs=,tag:KnJVy7oj2FXW2QNOK4CMGA==,type:str]
        passwords: ENC[AES256_GCM,data:2NaZYEHly6QclBkLe0Q/XNtBc+zFsailJl81rL6+e4+T1zmj+NHpo0EXa7gd08ZBE6yXaU1CmKlurQe0D1Do8BmoMcAuD3omS7bKWfIwz9Rpp0WtcOqILCwPviFx,iv:u9ffME+FUcbtmW+rNaEizc9Kf+ajc3FFXoT9tixmcQQ=,tag:G8zPT7WDR4+VC2HuMPeBFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f38l3w2h64surqtq8qtcqqg9lfs7qqmtw8g9xp22fwl4esgcyvzsv4yjsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZDFzbnBQajZoZWo2SHk4
            SGJWbnhuWDltRVluZjNIek1OU1Qxc2laZmpjCmtGYWZvL3FvcVRseERGVXpGei82
            cEdjdzd5dkJBWnZvTE8yUVA4OW9LM1EKLS0tIHErTUUyUkRRV3lNUG1lRWVPQVBy
            NU9kZ0FHT2tNVFVVSjBtSThjMndQNE0Kmyc30YYy2RIe6cMS7alCQL8b6WIqEiFw
            tN1J0aUcwsk80yV9TG8MW9miQnq8vbPsfaV9fBmRwHrscJVMIrmzsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-28T16:38:36Z"
    mac: ENC[AES256_GCM,data:06+w3dhfkFVXuLQ2iiWuJ2Bt78zNnd5tcEUr5RiZt8ZUSOtyfe1KdNWT0k4Plk/zaI7JrUQlPVHbAW7of/GAPh1abr8LVmlemH8Dh0UvU0ybvg9WoYxOSkx5e4+H5ogYNfdZ3541TMAemxjin637OzHP30si1kpUggOo2vCFrxc=,iv:MB+hRwkP9riKIMGsYvyKG+1KZPPL7JFgDorSN1A95qs=,tag:9kwuR6ccKsVhpOXRJyORQg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
