apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-route
  namespace: default
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sso.unrelated.family`)
      kind: Rule
      services:
        - name: authentik-server
          port: 80
  tls:
    secretName: unrelated-family-tls