apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: portainer
      sourceRef:
        kind: HelmRepository
        name: portainer
        namespace: default
      interval: 1m
  values:
    # Default values for portainer.
    # This is a YAML-formatted file.
    # Declare variables to be passed into your templates.

    replicaCount: 1

    # If enterpriseEdition is enabled, then use the values below _instead_ of those in .image
    enterpriseEdition: 
      enabled: true
      image:
        repository: portainer/portainer-ee
        tag: 2.19.4
        pullPolicy: Always
    serviceAccount:
      annotations: {}
      name: portainer-sa-clusteradmin

    service:
      # Set the httpNodePort and edgeNodePort only if the type is NodePort
      # For Ingress, set the type to be ClusterIP and set ingress.enabled to true
      # For Cloud Providers, set the type to be LoadBalancer
      type: ClusterIP

    persistence:
      enabled: true
      size: "10Gi"
      annotations: {}
      storageClass: longhorn
      existingClaim:
