apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 5m
  chart:
    spec:
      valuesFrom:
        - kind: ConfigMap
          name: hostname
          valuesKey: "rancher.local.unrelated.family"
      chart: rancher
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: cattle-system
      interval: 1m
