apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-pvc
  namespace: default
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi