kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: homepage-secret
    namespace: default
stringData:
    HOMEPAGE_VAR_PIHOLE_API_KEY_1: ENC[AES256_GCM,data:4Upk6KHJ39LKpK1CrSd9Mt7oxajgtVJE9Yj1Hlmm6ZVokJ7ulvuNgvwDOcf4MM42N+eo5uIC3gdomgFFK4qF5w==,iv:kLfaQ3Eur4BuFzzrK/iHnWwInjhuQEdZV3oaPETtKDQ=,tag:r1+4FEiokA+DcBysWdWKug==,type:str]
    HOMEPAGE_VAR_PIHOLE_API_KEY_2: ENC[AES256_GCM,data:qIwpsSJS6o/9Y0ap1W0qEAgpM/MbICSOEi3ek2Wlnm2vK5TUQt1Gk1reqGQfNpKqxfARW6KmS8HkygOEYnO1eA==,iv:/715MqlH3l5SIMG+2rB2DhWYW5YaYaHgkwln+d0XEtk=,tag:AW6dttN01wz8Zmc/LLkAeQ==,type:str]
    HOMEPAGE_VAR_PIHOLE_API_KEY_3: ""
    HOMEPAGE_VAR_PIHOLE_URL_1: ENC[AES256_GCM,data:jaWkur7QCTy4WAXPfXdMwXZxi3Y4l8M=,iv:7N5rWKjKmRGId43Fl8eq2V7mr7/3kcs9BdPc024WKnI=,tag:AXcr6GmYpnoNAJoXj6Nhew==,type:str]
    HOMEPAGE_VAR_PIHOLE_URL_2: ENC[AES256_GCM,data:sdWxmKrcqL3RRclMHxXgrB5vsPrsoQSf,iv:dFIHzIuj/8D8NKH3swY1MpcxUVpFxAM/+C4/5o9TSqU=,tag:tGiK1CNs32m7DUlLsKU/7A==,type:str]
    HOMEPAGE_VAR_PIHOLE_URL_3: ""
    HOMEPAGE_VAR_PLEX_url: ENC[AES256_GCM,data:/1a1Lo/1Mrazydc16Jf0SIJpjXUX9Fs=,iv:MHQDaQza7PqMxGnulk2W9Mxe6rdmmknu3hWNQcgFs4Q=,tag:S27V+7lld5Rq2lD8eNnTeg==,type:str]
    HOMEPAGE_VAR_PLEX_API_TOKEN: ENC[AES256_GCM,data:e4uUnCMgYq51J3PyXBJPOjAz9xk=,iv:GcILzhsGudPcxsOUdi76Qddh0veKP9JhN++h+NwPzuU=,tag:eIScrQ32e5gxGtwpy4K2OQ==,type:str]
    HOMEPAGE_VAR_TAUTULLI_url: ""
    HOMEPAGE_VAR_TAUTULLI_API_key: ""
    HOMEPAGE_VAR_HDHOMERUN_url: ""
    HOMEPAGE_VAR_HOME_ASSISTANT_url: ""
    HOMEPAGE_VAR_HOME_ASSISTANT_API_key: ""
    HOMEPAGE_VAR_TRUENAS_url: ""
    HOMEPAGE_VAR_TRUENAS_API_key: ""
    HOMEPAGE_VAR_UNIFI_NETWORK_url: ENC[AES256_GCM,data:DGfaMtIou5jvqlqJazJgIZX+hEs=,iv:pJ2BHrpDIcjS8zsYgz798eVQL66SkJ1qPmgJ16gBX84=,tag:OR4xjMkI1HkLkiclz7YFWQ==,type:str]
    HOMEPAGE_VAR_UNIFI_NETWORK_username: ""
    HOMEPAGE_VAR_UNIFI_NETWORK_password: ""
    HOMEPAGE_VAR_UNIFI_PROTECT_url: ENC[AES256_GCM,data:BxI5vVy0SFzeUhPKXYwxKJhaCig=,iv:SKGvFts14LHPO+VMeiIs150s1PkDWzbFCRYlypviqXY=,tag:5IWTq5K13lKKPB+tMA6HCQ==,type:str]
    HOMEPAGE_VAR_UPTIME_KUMA_url: ENC[AES256_GCM,data:eEyaySti39Ks8tCX91MGxo675LayvDfHaHUbgLl5Fw==,iv:8bOWIZx0gzS/PbdpyTffPSFdFQE6f8wuMOk8XS65F1c=,tag:oWmmiMVm9znszufgw+kguA==,type:str]
    HOMEPAGE_VAR_MINIO_url: ""
    HOMEPAGE_VAR_RACNHER_url: ""
    HOMEPAGE_VAR_LONGHORN_url: ENC[AES256_GCM,data:04YuUwIDVoGCkkI2Ut3yCgSC0wK1vk4sYOMIJJ9xL4fEy/Uad3V6,iv:YE3GH/S5TddHMCpVwyvnwHLhwPVOyJAbrK+dIHkORV0=,tag:jFeLKBx8TPlsFz9HAC/MdQ==,type:str]
    HOMEPAGE_VAR_PORTAINER_url: ENC[AES256_GCM,data:ddaqjL/7BfEqbKL3k6VYYwcx0hmWjnkJ0ZHxTZI7qrspNw==,iv:3KgzHfVLebrObKHnqOZxehxjkkwiQvv0cHSqUHpQh/M=,tag:x0hz0YS7uoIhaUafvKd23Q==,type:str]
    HOMEPAGE_VAR_PORTAINER_API_key: ENC[AES256_GCM,data:zZbVJN4kle5J5GTjWjKFLLSe2nAo2I7PYrxk0tSOmsrZvaV3UsNmTXkejta+qYAL,iv:sw+ey1xdz6yok/3Mvuowincwd9SeP8YN3snMG9nN1To=,tag:Xb+BGJ57ZU6U+3W93Q+50g==,type:str]
    HOMEPAGE_VAR_PROXMOX_url: ENC[AES256_GCM,data:5iPjcz3uftIt0wD+RZglZAueRneryZ1MvHsXTEw9yg==,iv:RiCcb1Hm5YcQy5UvrlZpJm+K0fxM6TZtXoKjeQ+v7BU=,tag:pXYtqjsOZS3wDtn483nh9A==,type:str]
    HOMEPAGE_VAR_PROXMOX_USER: ENC[AES256_GCM,data:XMmwZmYtRQe4s6xzTFqDFg==,iv:HvSmvXdTLobi+D68JXN0lXTVh+r6Ivvx86KvvWc2bcs=,tag:jo7ehSTlcgZVlDM3DhspFA==,type:str]
    HOMEPAGE_VAR_PROXMOX_API_key: ENC[AES256_GCM,data:fETSrGZR0BlQtvaEsfFpwgVaP7t2kVRuNH5d1UiEAc37AFmb,iv:dRAQ4WafgIv33jFpt1meZiIC5i5tttNSEQ+2zSg5HIg=,tag:+XpVCfLoNHh8pXbTvRQbuQ==,type:str]
    HOMEPAGE_VAR_UPTIME_ROBOT_API_key: ""
    HOMEPAGE_VAR_SCRYPTED_url: ""
    HOMEPAGE_VAR_PIKVM_url: ""
    HOMEPAGE_VAR_NETBOOT_url: ""
    HOMEPAGE_VAR_BROADLINK_CONTROL_url: ""
    HOMEPAGE_VAR_IPMI_1_url: ""
    HOMEPAGE_VAR_IPMI_2_url: ""
    HOMEPAGE_VAR_UPS_1_url: ""
    HOMEPAGE_VAR_UPS_2_url: ""
    HOMEPAGE_VAR_SHLINK_url: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f38l3w2h64surqtq8qtcqqg9lfs7qqmtw8g9xp22fwl4esgcyvzsv4yjsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndjRsbUZkREhUTWdvbWZT
            YXNNNTl0OUFiTFBiM21DZDNDK1UwMVQzM2pZCkV1WnpHTzlGQVhjRU0yRUZXTUNa
            R3NnYnJLMlhWWWNuSVRjQ3pFNGlXdWcKLS0tIHBsR3l3SWxKMG54OEpiaUZlY011
            dnVJTlo1bnVhOXVTU2RNeHhnR3ZmeVkKBhdcI2yL7Mss3BQgjVK4ry6L/My1lBt/
            9czBKFDqgUlf/Qgai18Zv2gzbgQ/saDbRuBaEBDUKsjZ5a332or+Pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-17T03:07:54Z"
    mac: ENC[AES256_GCM,data:O+cmNDeUcaWZaKbUpHpSt/xJT8gRjVnb8tw6fX6evXc00clmb86LDRes8R+72D46T1ulbWbMyx6ey97lBI/fl0MD26slaB4lmRdC8F7Xu44HJqrIItZQp5xVrywLKvnYEcuodSdbka0+sC0VzWdjaJyp2AmzaU0dlKfrhGY8p6Q=,iv:gfwAVpLCnbRR4UfXyKfYM6Ylz0Hrlcbe8LJ6ItLUs1s=,tag:fcEQVFUVYSWwv++LN6chFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
