apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-stack
  namespace: database
spec:
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: database
      interval: 1m
  values:
    grafana:
      enabled: true
    prometheus:
      enabled: true
      alertmanager:
        persistentVolume:
          enabled: false
      server:
        persistentVolume:
          enabled: false
    loki:
      persistence:
        enabled: true
        storageClassName: longhorn
        size: 5Gi